name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the Docker image'
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        IMAGE_TAG=${{ github.event.inputs.tag || 'latest' }}
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/webssh:$IMAGE_TAG

    - name: Push the Docker image to Docker Hub
      run: |
        IMAGE_TAG=${{ github.event.inputs.tag || 'latest' }}
        docker push ${{ secrets.DOCKER_USERNAME }}/webssh:$IMAGE_TAG
